#!/bin/bash
set -euo pipefail

case "$1" in
    start)
        if [[ -f /opt/yt-dl/V2_convert_yt.py ]]; then
            cd /opt/yt-dl
            python3 /opt/yt-dl/V2_convert_yt.py 
        else
            echo "Error: /opt/yt-dl/V2_convert_yt.py not found or not executable"
            exit 1
        fi
        ;;
    update) cd /opt/yt-dl ; ./update.sh ;;
    *)
        echo "Usage: ldmb start"
        exit 1
        ;;
esac
